spring:
  application:
    name: account_life
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/account_life?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    pool:
      max-idle-time: PT30S
  sql:
    init:
      mode: always
  mail:
    host: imap.qq.com # IMAP服务器地址
    port: 993 # 143 # 993 # IMAP SSL端口
    username: 772965502@qq.com # 邮箱账号
    password: deoirnadugwdbbji # UMPZf3nZYgdvJA46 # 邮箱授权码
    properties:
      mail:
        imap:
          ssl:
            enable: true
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
server:
  port: 8081
logging:
  level:
    io.r2dbc.spi.ConnectionFactory: DEBUG
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    io.r2dbc.mysql.QUERY: DEBUG